name: jwt_io
description: JSON Web Tokens are an open, industry standard RFC 7519 method for representing claims securely between two parties.
version: 1.1.4
homepage: https://github.com/glynskyi/jwt-io

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.2